apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-1-0-0-1
  # namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app-1-0-0-1
  template:
    metadata:
      labels:
        app: register-app-1-0-0-1
    spec:
      containers:
        - name: register-app
          image: 2swapna/register-app:1.0.0-4
          ports:
            - containerPort: 8080
          resources: {}
