apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app:1.0.0-1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app:1.0.0-1
  template:
    metadata:
      labels:
        app: register-app:1.0.0-1
    spec:
      containers:
        - name: register-app:1.0.0-1
          image: ashfaque9x/register-app:1.0.0-1
          ports:
            - containerPort: 8080
          # Empty resources map is safer than 'null'
          resources: {}
