apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app:1.0.0-5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app:1.0.0-5
  template:
    metadata:
      labels:
        app: register-app:1.0.0-5
    spec:
      containers:
        - name: register-app:1.0.0-5
          image: 2swapna/register-app:1.0.0-3
          ports:
            - containerPort: 8080
