apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  namespace: register-app
spec:
  type: NodePort
  selector:
    app: register-app-1-0-0-1   # must match Deployment labels
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30663
